#!/usr/bin/env python3
"""Generate Ansible vars YAML from Terraform output JSON."""

from __future__ import annotations

import json
import sys
from pathlib import Path


def main() -> None:
    default = Path("infra/terraform/homecoin/deployment-outputs.json")
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else default
    if not src.is_file():
        print(f"terraform outputs not found: {src}", file=sys.stderr)
        raise SystemExit(1)

    raw = json.loads(src.read_text(encoding="utf-8"))
    values = {key: entry.get("value") for key, entry in raw.items()}

    lines = ["# Generated by infra/scripts/generate_ansible_vars.py — do not edit"]
    for key in sorted(values):
        value = values[key]
        if value is None or value == "":
            continue
        lines.append(f"{key}: {json.dumps(value)}")

    print("\n".join(lines))


if __name__ == "__main__":
    main()
